### ISSUE TITLE
isAuthorized returning true for permissions that are not defined, routes, etc

### ISSUE THREAD

**Issue by chdev77** [matik12/aurelia-permission#4]
Using Aurelia CLI. Please help explain what I'm doing wrong here.

**main.js**
    import environment from './environment';
    import { PermissionStore, Configuration } from 'aurelia-permission';
    import { LmsServices } from 'services/lmsServices';
    import { HttpWrapper } from 'services/httpWrapper';
    import { HttpClient } from 'aurelia-fetch-client';
    import jwtDecode from 'jwt-decode';
    import { log } from 'resources/leadcube-logger';
    import {Container} from 'aurelia-dependency-injection';
    
    const agent = {
      id: 1,
      permissions: [
        'AccessOne',
        'AccessTwo',
        'listUsers'
      ]
    };
    
    const userPromise = new Promise(resolve =>{
      let container = Container.instance;
      container.registerInstance('httpClient', new HttpClient());
      container.registerInstance('httpWrapper', new HttpWrapper(container.get('httpClient')));
      container.registerInstance('lmsService', new LmsServices(container.get('httpWrapper')));
      let lmsService = container.get('lmsService');
    
      lmsService.getToken(csrid)
        .then(response => {
          let claimsPayload = jwtDecode(response.token);
          log.info(`Agent Raw Token: ${JSON.stringify(response)}`);
          log.info(`Agent Token Claims: ${JSON.stringify(claimsPayload)}`);
        });
      resolve(agent);
    });
    
    export function configure(aurelia) {
      this.permissionStore = PermissionStore;
      this.configuration = Configuration;
      aurelia.use
        .standardConfiguration()
        .feature('resources')
        .plugin('aurelia-dialog')
        .plugin('aurelia-validation')
        .plugin('aurelia-permission', (permissionStore, configuration) => configurePermissions(aurelia, permissionStore, configuration));
    
      if (environment.debug) {
        aurelia.use.developmentLogging();
      }
      userPromise.then(() => {
        aurelia.start().then(() => aurelia.setRoot());
      });
    }
    
    function configurePermissions(aurelia, permissionStore, configuration) {
      configuration.useDefaultRedirectRoute('not-authorized');
    
      userPromise
        .then((user) => {
          log.info(`userPromise result of user permissions from api: ${JSON.stringify(user)}`);
          const allApplicationPermissions = ['addUsers', 'deleteUsers', 'listUsers'];
          permissionStore.useDefaultDefinition(user.permissions);
          permissionStore.definePermissions(allApplicationPermissions);
          // permissionStore.definePermissions(
          //   allApplicationPermissions,
          //   // simple custom definition, the same function for all permissions
          //   // it only checks if particular permission is included in user's permissions array
          //   // if permissions need to have different definitions, then use
          //   // permissionStore.definePermissions() method for each specific permission
          //   (permission) => {
          //     log.info('Custom definition function');
          //     log.info(`User Permissions: ${JSON.stringify(user.permissions)}`);
          //     return user.permissions.includes(permission);
          //   }
          // );
    
          return user;
        });
    }

**app.js**
    import { Router } from 'aurelia-router';
    import { inject } from 'aurelia-framework';
    import { AuthorizationService } from 'aurelia-permission';
    import { log } from 'resources/leadcube-logger';
    
    @inject(Router, AuthorizationService)
    export class App {
      constructor(router, authorizationService) {
        // this.message = 'Hello World!';
        this.router = router;
        this.authorizationService = authorizationService;
        log.info(`isAuthorized: ${this.authorizationService.isAuthorized('asdf')}`);
      }
    
      configureRouter(config, router) {
        config.title = 'LeadCube';
        config.map([
          { route: '', redirect: 'home'},
          //{ route: '', redirect: 'home'},
          //{ route: 'home', moduleId: 'common/home', name: 'home', title: 'LeadCube Home', nav: true, setting: { permission: { only: 'asdf', redirectTo:     'chat'}}},
          { route: 'home', moduleId: 'common/home', name: 'home', title: 'LeadCube Home'},
          { route: 'chat', moduleId: 'chat/chat', name: 'chat', title: 'Chat'}
        ]);
        this.router = router;
      }
    }

I think there is a bug in the isAuthorized method.
![aurelia-permission-bug](https://user-images.githubusercontent.com/7691322/34839683-2797fdcc-f6c8-11e7-8eb4-b32bff920948.PNG)

**Comment by matik12** [comment]
Hi @chdev77 

thanks for your notes. To answer your questions:

1. When you check that user has permission that was not defined during plugin configuration, then `isAuthorized` will return true. This is by design, because this particular permission was not defined you can access whatever you like i.e. in your use case `authorizationService.isAuthorized('asdf')` should return true. What's the reason to check permission that was not defined and plugin doesn't know how to check if user has the requested permission?

2. What is more `isAuthorized('listUsers')` will return true, because this permissions is defined in the configuration, so plugin knows how to check it
```
const allApplicationPermissions = ['addUsers', 'deleteUsers', 'listUsers'];
permissionStore.definePermissions(allApplicationPermissions);
``` 
And also current user returned from `userPromise` has this permission in the **permissions** array
```
const agent = {
  id: 1,
  permissions: [
    'AccessOne',
    'AccessTwo',
    'listUsers'
  ]
};
```
3. If you check permission that is not included in user's object i.e. `isAuthorized('addUsers')` then this should **return** false as expected.

I hope this clarify some things.

Thanks and take care,
Mat

**Comment by chdev77** [comment]
@matik12 Thank you! I understand now and it is all working.  Note: the 'asdf' was just test code :)
